### ISSUE TITLE
Support Multiple Completion Backends

### ISSUE THREAD

**Issue by dylanjm** [canatella/xwwp#1]
Hi, I made the comment on your reddit post for multiple completion backends. 

I have a WIP PR started to add support for any completion backend. I bassically took it from: 

https://github.com/bbatsov/projectile/blob/master/projectile.el

I'm not quite sure how to handle `:update-fn` and the `xwidget-plus-follow-link-highlight` function. I can push my PR to give you an idea.

**Comment by canatella** [comment]
Yeah that is the whole problem. But a version without the highlighting might be a first step. I'm writing some tests this evening and I've split up the source code but I'll gladly have a look at your PR anyway. Thank you!

**Comment by canatella** [comment]
So it supports the default system, ido, ivy and helm now :)
