### ISSUE TITLE
Can't change text color for links

### ISSUE THREAD

**Issue by Townk** [canatella/xwwp#13]
I'm trying to customize the colors for links with the following code:

```emacs-lisp
  (use-package! xwwp-follow-link
    :defer t
    :config
    (setq xwwp-follow-link-completion-system 'ivy
          xwwp-follow-link-candidate-style '(("border" . "1px dashed blue")
                                             ("background" . "none"))
          xwwp-follow-link-selected-style '(("border" . "1px dashed #8ba1bc")
                                            ("background" . "#365479")
                                            ("color" . "#8ba1bc"))))
```

The result is this:

![CleanShot 2020-10-09 at 11 46 14](https://user-images.githubusercontent.com/1261/95609883-11955880-0a25-11eb-830f-56f0f3c3efe5.png)

Notice that the text is still being drawn in gray.

**Comment by canatella** [comment]
There is nothing magic here, all that the package is doing is injecting the CSS into the browser web page so if the text is still grey it means that it is overridden for some reason by the web page at some point . Maybe try with `!important`. But I don't think there is anything I can do here.
