### ISSUE TITLE
`C-g` during `xwwp-follow-link` doesn't remove the blue boxes.

### ISSUE THREAD

**Issue by kchanqvq** [canatella/xwwp#9]
An improvement might be to remove them.

**Comment by canatella** [comment]
I use them to focus the eyes on the various link when searching. You can remove it by customizing `xwwp-follow-link-candidate-style`. For the red boxes it is `xwwp-follow-link-selected-style`.

**Comment by canatella** [comment]
Reopening because they should still be removed on `C-g` though.

**Comment by canatella** [comment]
I've been testing this and it is working for me they are removed. I call `xwwp-follow-link` then enter a few chars to have the links highlighted then `C-g` and everything is back to normal. What are the exact steps to reproduce the problem? Can you reproduce it on the master branch ? 

It is handled by the `unwind-protect` in `xwwp-follow-link-callback`

**Comment by kchanqvq** [comment]
I'm using xwwp and helm in `emacs -q`.

The usage of `unwind-protect` is not correct (it's doing nothing there),
it should be
```
(unwind-protect
        (xwwp-follow-link-read xwwp-follow-link-completion-backend-instance
                               "Link: " links
                               (apply-partially #'xwwp-follow-link-trigger-action xwidget)
                               (apply-partially #'xwwp-follow-link-update xwidget))
      (xwwp-follow-link-cleanup xwidget))
```
This fixed it for me. I'll include it in my PR altogether.
